/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyLogsRouteImport } from './routes/my-logs'
import { Route as MapRouteImport } from './routes/map'
import { Route as LogRouteImport } from './routes/log'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowUnitRouteImport } from './routes/know.$unit'

const MyLogsRoute = MyLogsRouteImport.update({
  id: '/my-logs',
  path: '/my-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowUnitRoute = KnowUnitRouteImport.update({
  id: '/know/$unit',
  path: '/know/$unit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/my-logs': typeof MyLogsRoute
  '/know/$unit': typeof KnowUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/my-logs': typeof MyLogsRoute
  '/know/$unit': typeof KnowUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/my-logs': typeof MyLogsRoute
  '/know/$unit': typeof KnowUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/log' | '/map' | '/my-logs' | '/know/$unit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/log' | '/map' | '/my-logs' | '/know/$unit'
  id: '__root__' | '/' | '/about' | '/log' | '/map' | '/my-logs' | '/know/$unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LogRoute: typeof LogRoute
  MapRoute: typeof MapRoute
  MyLogsRoute: typeof MyLogsRoute
  KnowUnitRoute: typeof KnowUnitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-logs': {
      id: '/my-logs'
      path: '/my-logs'
      fullPath: '/my-logs'
      preLoaderRoute: typeof MyLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/know/$unit': {
      id: '/know/$unit'
      path: '/know/$unit'
      fullPath: '/know/$unit'
      preLoaderRoute: typeof KnowUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LogRoute: LogRoute,
  MapRoute: MapRoute,
  MyLogsRoute: MyLogsRoute,
  KnowUnitRoute: KnowUnitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
